[package]
name = "linkerd2-dns"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3"
linkerd2-dns-name = { path = "./name" }
linkerd2-stack = { path = "../stack" }
tower = "0.3"
trust-dns-resolver = { version = "0.19", default-features = false, features = ["system-config", "tokio-runtime"] }
tracing = "0.1"
tracing-futures = "0.1"
pin-project = "0.4"